### ISSUE TITLE
Creating an InputEventListener always initialises the PiFace board

### ISSUE THREAD

**Issue by YoungJules** [piface/pifacedigitalio#22]
Could it be changed so we can pass an init_board param:
listener = pifacedigitalio.InputEventListener(init_board=False)

Thanks!

**Comment by tompreston** [comment]
You can't pass an init_board parameter but you *can* pass an already initialised (or not) board like so:

    import pifacedigitalio
    pfd = pifacedigitalio.PiFaceDigital(init_board=False)
    pifacedigitalio.InputEventListener(chip=pfd)
