### ISSUE TITLE
raspberry pi 2 and piface 2 - board not found

### ISSUE THREAD

**Issue by wiiikiii** [piface/pifacedigitalio#23]
I bought all new and tried to run some sample code.
But the board will not be found not under X nor on the
console. I've tried python and ruby as well.

The python output is

    root@raspberrypi:/home/pi# python
    Python 2.7.3 (default, Mar 18 2014, 05:13:23)
    [GCC 4.6.3] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import pifacedigitalio as pfio;
    >>> pfio.init();
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python2.7/dist-packages/pifacedigitalio/core.py", line 166, in init
        raise failed_boards[0]
    pifacedigitalio.core.NoPiFaceDigitalDetectedError: No PiFace Digital board detected (hardware_addr=0, bus=0, chip_select=0).
    >>>

any ideas?

    root@raspberrypi:/home/pi# uname -a
    Linux raspberrypi 3.18.5-v7+ #225 SMP PREEMPT Fri Jan 30 18:53:55 GMT 2015 armv7l GNU/Linux

    root@raspberrypi:/home/pi# dpkg -l | grep pif
    ii  python-pifacecommon                   4.0.0-1                                 all          The PiFace common functions module.
    ii  python-pifacedigitalio                3.0.4-1                                 all          The PiFace Digital I/O module.
    ii  python3-pifacecommon                  4.0.0-1                                 all          The PiFace common functions module.
    ii  python3-pifacedigital-scratch-handler 2.0.5-1                                 all          The PiFace Digital Scratch Handler.
    ii  python3-pifacedigitalio               3.0.4-1                                 all          The PiFace Digital I/O module.

    root@raspberrypi:/home/pi# gem list
    *** LOCAL GEMS ***
    ffi (1.9.6)
    piface (0.4.1)

**Comment by tompreston** [comment]
Did you install using the guide [here](http://pifacedigitalio.readthedocs.org/installation.html)? Is the SPI module enabled?

Can you post the output of:

    lsmod

Try running:

    raspi-config

And navigating to Advanced > Enable SPI > Enable > Reboot.

**Comment by wiiikiii** [comment]
works now with a new install raspian 2015-05-05 fine. thanks you.
