### ISSUE TITLE
Compatible with Piface RTC Module?

### ISSUE THREAD

**Issue by cathalgarvey** [piface/pifacedigitalio#25]
This should really be in the FAQ! I'm building a time-based code-lock with PiFace and an RPi (code will be published with a FL license, not to worry!), and because codes are time-critical I'd like a real-time clock. If I know for a fact that the RTC from PiFace is compatible with the Piface DIO board, I'll buy that, but I can't find mention of that in the RTC docs or on either issue tracker. It seems a strange omission..

Thanks!

**Comment by tompreston** [comment]
PiFace RTC is compatible with PiFace Digital. This is mentioned on the [web page](http://www.piface.org.uk/products/piface_clock/) but we'll update the docs too, thanks.
