### ISSUE TITLE
Raspberry pi 2 Piface digital 2

### ISSUE THREAD

**Issue by drmod3** [piface/pifacedigitalio#29]
There seems to be a problem with simple InputEventListener.
The emulator works as well as output pins and input pins.
After trying several programs, I attempted the examples.
Blink works, presslights does not, whackamole does.

Two boards and 3 SD cards have been tried, with update and upgrade.
Have I missed something?
Thanks

**Comment by drmod3** [comment]
Additional information has been observed.
When rebooting, an error flashes by which says:  
"Error loading module spi-bcm 2708 no such module."

lsmod shows: spi_bcm2835      4253    0
also shows:    snd_bcm2835    19761   6

/lib/modules/4.0.8-v7+/kernel/drivers/spi/ has two files: spi-bcm2708.ko and spi-bcm2835.ko
The actual device shows to be bcm2709.

Thanks for any help on resolved the interrupt issue, which appears to be related.

**Comment by tompreston** [comment]
Did you manage to solve this in the end? I've just done a fresh install of Raspbian and `presslights.py` works for me.
