### ISSUE TITLE
Raspberry Pi 2, Piface Digital 2 interrupt

### ISSUE THREAD

**Issue by drmod3** [piface/pifacedigitalio#30]
There seems to be a problem with simple InputEventListener.
The emulator works as well as output pins and input pins.
After trying several programs, I attempted the examples.
Blink works, presslights does not, whackamole does partially.
Two boards and 3 SD cards have been tried, with update and upgrade following instructions.

Have I missed something?

Additional information has been observed.
When rebooting, an error flashes by which says:
"Error loading module spi-bcm 2708 no such module."

lsmod shows: spi_bcm2835 4253 0
 also shows: snd_bcm2835 19761 6

/lib/modules/4.0.8-v7+/kernel/drivers/spi/ has two files: spi-bcm2708.ko and spi-bcm2835.ko
The actual device shows to be bcm2709.

Thanks for any help on resolved the interrupt issue, which appears to be related to the bcm module

**Comment by tompreston** [comment]
`presslights.py` seems to be working for me after a fresh install of wheezy. Are you using the latest software?

    sudo apt-get update && sudo apt-get upgrade

**Comment by dbrb2** [comment]
I have just had this happen to me after a raspbian apt-get-update/upgrade cycle
Initially spi dodn't work at all posy upgrade, with the error given above, until I changed my modprobe line to 2835

Now I can read and write pins fine, but interrupts are still not working....any ideas?

**Comment by dbrb2** [comment]
Ah - solution found:
http://www.element14.com/community/message/139528/l/re-piface-digital-2--setup-and-use#139528

**Comment by tompreston** [comment]
Glad you got this sorted!
