### ISSUE TITLE
Relays don't swicth off after being on for more than 5 minutes

### ISSUE THREAD

**Issue by rafaelbuiu** [piface/pifacedigitalio#31]
I noticed that the indicator LED goes on/off but the relay itself doesn't.

If I slap the raspberry pi box it turns off. It seems to be a physical issue but I already tested all the other 3 pifaces i have and they behave the same way.

Have someone faced this issue before? 

Setup: Raspberry 2 and Piface Digital 2

**Comment by tompreston** [comment]
> If I slap the raspberry pi box it turns off.

The Pi turns of or the PiFace turns off?

I can't seem to replicate your problem - I've just left one of my PiFace Digital relay's on for about an hour and it switched off fine when I ran the code. Maybe you have faulty units? Have you tried contacting your supplier?

**Comment by rafaelbuiu** [comment]
The indicator LED works fine but the relay itself doesn't switch off.
But when I slap the relay (raspberry pi, piface, etc) the relay switches off only if the LED indicator state is off.

I think it would be too much coincidence if I all my units are faulty.

Is there any bug related about to the version of something (raspbian, piface, kernel, etc)?

Thanks for your reply.

**Comment by tompreston** [comment]
How much current are you putting through the relays? It is possible to break them if you use too much.

I've not heard of any relay-specific bugs. They are controlled in parallel with the LEDs so if your LED is working then the software and microchips are working.

**Comment by rafaelbuiu** [comment]
I did an other test today with a regular relay (not Piface's) and it behaves the same way. For sure it is not a Piface's issue.

Sorry for that!
