### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by deobrien1962** [piface/pifacedigitalio#35]
Having a problem with the installation of piface on a Pi 3

Went through all the steps and get the following form the console
pi@raspberrypi:~ $ sudo apt-get install python{,3}-pifacedigitalio
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python-pifacedigitalio
E: Unable to locate package python3-pifacedigitalio

Tried cloning and I get the same result.

**Comment by Admiraldr** [comment]
Same here. 

I use the latest Raspbian (stretch) installation.
I noticed on another RPi (with jessie) that the packets could be installed successfully.

**Comment by Admiraldr** [comment]
Seems that the packages are not part of Raspbian (stretch).
As a workaround I installed an older Raspbian (jessie). There I was able to install the packages.

Would be really great if the piface packages are added to Stretch as well.

**Comment by deobrien1962** [comment]
Agreed...  It would save all a great deal of time.

**Comment by netkruzer** [comment]
Agreed. Just installed a fresh install of Raspbian Stretch and sudo apt-get will not install the piface modules.

**Comment by jakorten** [comment]
The same issue here...

**Comment by rudyvan** [comment]
I had the same issue and it appears that the SPI bus speed increased from 100KHZ to 125KHZ on stretch.
After some searching i have found a alternative solution which works for piface2.
it is a pure python script and it works on raspberry stretch, is faster and uses the same syntax, so minimal programming changes:

https://github.com/bulletmark/pifaceio.git

with thanks to bulletmark!

**Comment by rijmenantspj** [comment]
I had the same issue on Raspbian GNU/Linux 9 (stretch). Nevertheless, the workaround from @jakorten worked for me.

For Python:
`sudo pip install pifacecommon`
`sudo pip install pifacedigitalio`

For Python3:
`sudo pip3 install pifacecommon`
`sudo pip3 install pifacedigitalio`

Please note, you need to make sure you have PIP installed first. If not, the following command will install PIP for both Python and Python3.

`sudo apt-get install python{,3}-pip`

**Comment by SiAust** [comment]
Hello, I'm struggling to get my Raspberry Pi with PiFace Digital 2 working. I have the same issue as the OP but following all the advice in this thread hasn't helped. I would like to install the emulator to test some buttons a friend has set up on a breadboard connected to the PiFace.

I have run
```
sudo pip install pifacecommon
sudo pip install pifacedigitalio
For Python3:
sudo pip3 install pifacecommon
sudo pip3 install pifacedigitalio
```
and
```
https://github.com/bulletmark/pifaceio.git
```
Installed all the libraries successfully. What is the next step please? 

Raspberry Pi 3 Model Model B V1.2
Raspbian GNU/Linux 10 (Buster)

**Comment by bulletmark** [comment]
@SiAust I am the author of the [piface](https://github.com/bulletmark/pifaceio.git) package. Note it is completely independent to pifacedigitalio and is simply an alternative if you want to try something else. It is inappropriate to discuss it here so if you want help with that, please [raise an issue](https://github.com/bulletmark/pifaceio/issues) there and I will help you out.

**Comment by SiAust** [comment]
@bulletmark Thank you. I will continue a conversation on your repo, I appreciate it.

**Comment by tompreston** [comment]
The package isn't in debian, so `apt` won't work.

Use `pip`, which is the official way to install Python packages. https://pypi.org/project/pifacedigitalio/

@bulletmark pifaceio looks great.

There's also a devicetree overlay if you want to write a driver for that. Might be simpler than crafting your own SPI packets - just let the kernel do it. https://github.com/raspberrypi/linux/pull/3794

**Comment by OutsourcedGuru** [comment]
> I had the same issue on Raspbian GNU/Linux 9 (stretch). Nevertheless, the workaround from @jakorten worked for me.
> 
> For Python:
> `sudo pip install pifacecommon`
> `sudo pip install pifacedigitalio`
> 
> For Python3:
> `sudo pip3 install pifacecommon`
> `sudo pip3 install pifacedigitalio`
> 
> Please note, you need to make sure you have PIP installed first. If not, the following command will install PIP for both Python and Python3.
> 
> `sudo apt-get install python{,3}-pip`

This approach worked for me. Also, you apparently need to visit `sudo raspi-config` and enable SPI, for example, in the Interfaces section and reboot.
