### ISSUE TITLE
SimpleWebControl

### ISSUE THREAD

**Issue by morrisond91** [piface/pifacedigitalio#37]
Hey,

does anyone know how to turn a relay on or off using the simplewebcontrol script?

**Comment by tompreston** [comment]
Maybe something like:
```
http://192.168.1.61:8000/?output_port=0x01
http://192.168.1.61:8000/?output_port=0x02
```

See the docs here https://pifacedigitalio.readthedocs.io/simplewebcontrol.html

**Comment by morrisond91** [comment]
Thanks.
