### ISSUE TITLE
Pifacedigitalio for C

### ISSUE THREAD

**Issue by bruji35** [piface/pifacedigitalio#38]
Hello,
I need the library Pifacedigitalio for C, Is there any version for this language?

I need to use the InputEventListener function but I can not find any equivalent for C.

Could you help me?

Thank you.

**Comment by tompreston** [comment]
Yep it's here https://github.com/piface/libpifacedigital

**Comment by bruji35** [comment]
Thank you!! but that library does not have InputEventListener, instead it is _pifacedigital_wait_for_input_, but this función stop the execution of the program and I need that the program to continue executing and when there is a change in an entry let me know.

**Comment by tompreston** [comment]
In the Python library, InputEventListener essentially implements an asynchronous I/O event listener (and not very well imo).

You will have to manage your own asynchronous I/O when using C. It uses `epoll` under the hood - maybe look for examples online of where people have used epoll asynchronously

**Comment by bruji35** [comment]
Ok, Thank you very much for your help, I will look for some solution.
