### ISSUE TITLE
Documentation - Examples

### ISSUE THREAD

**Issue by waterman480** [piface/pifacedigitalio#4]
Line 5 in examples starts off with board1.  Very confusing to noob, as factory setting is board0, ,and most noobs will only have one board.  Have seen complaints about this elsewhere.  Knew it was a doc problem, since Pi face worked on pfio under Python 2.7

**Comment by tompreston** [comment]
I'm not sure which line you're talking about, but please submit a merge request if you feel like something needs changing:
- http://pifacedigitalio.readthedocs.io/example.html
- https://github.com/piface/pifacedigitalio/blob/master/docs/example.rst
